### ISSUE TITLE
Any plan on supporting Prometheus exporter on gobmp

### ISSUE THREAD

**Issue by lordofire** [sbezverk/gobmp#182]
As BGP bmp client will publish the initialization message everytime gobmp restarted, I think gobmp internally could build a in-memory bgp peer state and route map, which could be exposed through API so that monitoring frameworks like Prometheus could collect it for monitoring and alerts. It is much scalable and flexible compared to adding SNMP monitoring for all different network devices.

**Comment by sbezverk** [comment]
goBMP was designed based on 2 main principles:  - to be as stateless as possible in order to process large amount of routing information; - to be just a collector and leave all application specific logic outside.  We are looking to add other types of publishers, if Prometheus supports a "push" model, when a client, goBMP for example, publishes or push to Prometheus server records constructed from routing information goBMP received, such model can easily be integrated into goBMP. In this case your monitoring application will work directly with Prometheus data or API.

**Comment by lordofire** [comment]
That makes sense. Thanks for your elaboration
